# Comment lines
# General makefile for c - choose PROG =   name of given program
# Here we define compiler option, libraries and the  target
CC= g++ -std=c++11 -Wall -Wextra -Wpedantic -larmadillo -lblas -llapack
CFLAGS=-I.





pro3_a: pro3_a.cpp
	${CC} -o pro3_a.exe pro3_a.cpp
