# Comment lines
# General makefile for c - choose PROG =   name of given program
# Here we define compiler option, libraries and the  target
CC= mpiCC -std=c++11 -Wall -Wextra -Wpedantic -larmadillo -lblas -llapack
CFLAGS=-I.








 pro3_ce: pro3_ce.cpp
	${CC} -o  pro3_ce.exe  pro3_ce.cpp
